Hw 24 2
ilya449/internet-shop pull request #3
Opened 2020-09-07 10:27 UTC by ilya449

2020-09-07 17:55 UTC, DariaPikul requested changes

2020-09-07 17:55 UTC, DariaPikul commented on src/main/java/com/internet/shop/Application.java
> +        System.out.println("Testing OrderService============================================");
Let's introduce a variable for the "====" separator

2020-09-07 17:55 UTC, DariaPikul commented on src/main/java/com/internet/shop/dao/impl/ShoppingCartDaoImpl.java
> +                        .equals(shoppingCart.getId()))
```suggestion
                .filter(i -> Storage.getShoppingCarts().get(i)
                        .getId().equals(shoppingCart.getId()))
```

2020-09-07 17:55 UTC, DariaPikul commented on src/main/java/com/internet/shop/service/impl/ShoppingCartServiceImpl.java
> +        shoppingCartDao.update(shoppingCart);
Reconsider simplifying of the method

2020-09-07 17:55 UTC, DariaPikul commented on src/main/java/com/internet/shop/service/impl/ShoppingCartServiceImpl.java
> +                        .format("There is no shopping carts for user with id:%d", userId)));
There is no need to throw an exception. If we try to get the value from a non-existent element, we'll receive an exception by default.

2020-09-07 17:55 UTC, DariaPikul commented on src/main/java/com/internet/shop/service/impl/ShoppingCartServiceImpl.java
> +                        .format("There is no shopping carts for user with id:%d", userId)));
```suggestion
                .get();
```

2020-09-07 17:55 UTC, DariaPikul commented on src/main/java/com/internet/shop/service/impl/UserServiceImpl.java
> +                        .format("Storage does not contain user with id:%d", id)));
Same here

2020-09-08 06:34 UTC, Sofasmile commented on src/main/java/com/internet/shop/Application.java
> +        System.out.println("Testing OrderService============================================");
I agree with Daria)

2020-09-08 06:34 UTC, Sofasmile commented on src/main/java/com/internet/shop/service/impl/OrderServiceImpl.java
> +    private ShoppingCartDao shoppingCartDao;
can we remove this field?

2020-09-08 06:34 UTC, Sofasmile commented on src/main/java/com/internet/shop/service/impl/OrderServiceImpl.java
> +    public List<Order> getUserOrders(Long userId) {
let's move this method to the dao layer

2020-09-08 06:34 UTC, Sofasmile commented on src/main/java/com/internet/shop/service/impl/ShoppingCartServiceImpl.java
> +        if (shoppingCart.getProducts().stream()
спробуй спростити цей метод, подібно до метода addProduct()

2020-09-08 06:34 UTC, Sofasmile commented on src/main/java/com/internet/shop/service/impl/ShoppingCartServiceImpl.java
> +    public ShoppingCart getByUserId(Long userId) {
let's move this method at the dao layer

2020-09-08 06:34 UTC, Sofasmile commented on src/main/java/com/internet/shop/service/impl/UserServiceImpl.java
> +                        .format("Storage does not contain user with id:%d", id)));
@DariaPikul Якщо прописувати власне кастомне повідомлення і передавати ід з яким виникла помилка, то можна залишити orElseThrow(), але якщо нічого не прописувати в параметрах, то краще використовувати просто get()

2020-09-08 07:54 UTC, ilya449 commented on src/main/java/com/internet/shop/Application.java
> +        System.out.println("Testing OrderService============================================");
Done

2020-09-08 07:56 UTC, ilya449 commented on src/main/java/com/internet/shop/service/impl/OrderServiceImpl.java
> +    private ShoppingCartDao shoppingCartDao;
Yes, removed

2020-09-08 07:57 UTC, ilya449 commented on src/main/java/com/internet/shop/service/impl/OrderServiceImpl.java
> +    public List<Order> getUserOrders(Long userId) {
Done

2020-09-08 07:57 UTC, ilya449 commented on src/main/java/com/internet/shop/service/impl/ShoppingCartServiceImpl.java
> +        if (shoppingCart.getProducts().stream()
Simplified

2020-09-08 07:58 UTC, ilya449 commented on src/main/java/com/internet/shop/service/impl/ShoppingCartServiceImpl.java
> +    public ShoppingCart getByUserId(Long userId) {
Done

2020-09-08 08:01 UTC, ilya449 commented on src/main/java/com/internet/shop/service/impl/ShoppingCartServiceImpl.java
> +                        .format("There is no shopping carts for user with id:%d", userId)));
I know, but I want to add my message to the exceptions

2020-09-08 12:34 UTC, Sofasmile approved these changes

2020-09-08 13:10 UTC, merged