Hw 26 part 1
ilya449/internet-shop pull request #5
Opened 2020-09-09 16:36 UTC by ilya449

2020-09-09 17:39 UTC, DariaPikul requested changes
Please, implement the method that allows users to add new products to DB.
We'll use it later for admins.

2020-09-09 17:39 UTC, DariaPikul commented on src/main/java/com/internet/shop/controller/RegistrationController.java
> +        if (pass.equals(repeatedPass)) {
What if we receive the empty Strings?

2020-09-09 17:39 UTC, DariaPikul commented on src/main/java/com/internet/shop/controller/AddProductController.java
> +        String name = req.getParameter("name");
Same check

2020-09-09 17:39 UTC, DariaPikul commented on src/main/java/com/internet/shop/controller/RegistrationController.java
> +            resp.sendRedirect(req.getContextPath() + "/");
We have to create the shopping carts at the moment of creating our users

2020-09-09 20:20 UTC, ilya449 commented on src/main/java/com/internet/shop/controller/RegistrationController.java
> +        if (pass.equals(repeatedPass)) {
I've missed it, thank you

2020-09-09 20:33 UTC, ilya449 commented on src/main/java/com/internet/shop/controller/RegistrationController.java
> +            resp.sendRedirect(req.getContextPath() + "/");
> Please, implement the method that allows users to add new products to DB.
> We'll use it later for admins.

I have the AddProductController that allows users to add products. But I forgot to put the link in index.jsp, thank you for your reminding

2020-09-09 20:36 UTC, DariaPikul commented on src/main/java/com/internet/shop/controller/RegistrationController.java
> +            resp.sendRedirect(req.getContextPath() + "/");
Then what about adding the products to the shopping cart?

2020-09-10 06:54 UTC, Sofasmile commented on src/main/java/com/internet/shop/controller/AddProductController.java
> +@WebServlet("/product/addition")
```suggestion
@WebServlet("/product/add")
```

2020-09-10 06:54 UTC, Sofasmile commented on src/main/java/com/internet/shop/controller/InjectDataController.java
> +@WebServlet("/injectData")
https://mate-academy.github.io/jv-program-fulltime/02_jdbc_and_servlets/checklist/hw_16_1.html

2020-09-10 06:54 UTC, Sofasmile commented on src/main/java/com/internet/shop/controller/RegistrationController.java
> +                && pass.length() > 0 && pass.equals(repeatedPass)) {
we can use html tags to check is the field empty
find the title: Input Restrictions
https://www.w3schools.com/html/html_form_input_types.asp

2020-09-10 06:54 UTC, Sofasmile commented on src/main/java/com/internet/shop/controller/AddProductController.java
> +        if (name.length() > 0 && price.length() > 0) {
https://www.w3schools.com/html/html_form_input_types.asp

2020-09-10 09:07 UTC, ilya449 commented on src/main/java/com/internet/shop/controller/RegistrationController.java
> +            resp.sendRedirect(req.getContextPath() + "/");
BuyProductController adds products to the shopping cart

2020-09-10 09:23 UTC, ilya449 commented on src/main/java/com/internet/shop/controller/RegistrationController.java
> +                && pass.length() > 0 && pass.equals(repeatedPass)) {
Added html tags, and Bohdan allowed not to remove this simple check

2020-09-10 10:45 UTC, Sofasmile approved these changes

2020-09-10 11:10 UTC, merged