created AuthenticationFilter, AuthenticationService, login.jsp and Lo…
ilya449/internet-shop pull request #9
Opened 2020-09-14 15:04 UTC by ilya449

…ginController

2020-09-14 20:11 UTC, Nokafan reviewed
Nice work ))

2020-09-14 20:11 UTC, Nokafan commented on src/main/java/com/internet/shop/web/filter/AuthenticationFilter.java
> +            .getInstance(UserService.class);
We don't need userService here.

2020-09-14 20:11 UTC, Nokafan commented on src/main/java/com/internet/shop/security/AuthenticationServiceImpl.java
> +    public User login(String login, String pass) throws AuthenticationException {
Just my opinion but maybe better do not use **pass** for the name?

2020-09-15 05:51 UTC, KseniiaMakarova requested changes

2020-09-15 05:51 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/controller/user/LoginController.java
> +            session.setAttribute("userId", user.getId());
let's make `userId` a constant

2020-09-15 05:51 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/security/AuthenticationServiceImpl.java
> +    public User login(String login, String pass) throws AuthenticationException {
```suggestion
    public User login(String login, String password) throws AuthenticationException {
```

2020-09-15 05:51 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/security/AuthenticationServiceImpl.java
> +        if (user.getPassword().equals(pass)) {
let's check all conditions inside `if` so that we could throw our Exception only once

2020-09-15 05:51 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/web/filter/AuthenticationFilter.java
> +
redundant empty line

2020-09-15 05:51 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/web/filter/AuthenticationFilter.java
> +
same

2020-09-15 05:51 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/web/filter/AuthenticationFilter.java
> +            .getInstance(UserService.class);
@Nokafan it is used below

2020-09-15 10:13 UTC, KseniiaMakarova approved these changes

2020-09-15 11:30 UTC, merged

2020-09-15 15:56 UTC, Nokafan commented on src/main/java/com/internet/shop/web/filter/AuthenticationFilter.java
> +            .getInstance(UserService.class);
Sorry, I didn't pay attention.